// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo00aeaXK3PAgj0xZLZHExWORY4bMs6lE',
    appId: '1:878367613942:web:0fb6e4e12e206c89529dd7',
    messagingSenderId: '878367613942',
    projectId: 'my-portfolio-9ff74',
    authDomain: 'my-portfolio-9ff74.firebaseapp.com',
    storageBucket: 'my-portfolio-9ff74.appspot.com',
    measurementId: 'G-7DC7KKRR5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXWEnTEMYt6lylznJ5Q0pixtC8DlQyfhA',
    appId: '1:878367613942:android:df8803ac0e032304529dd7',
    messagingSenderId: '878367613942',
    projectId: 'my-portfolio-9ff74',
    storageBucket: 'my-portfolio-9ff74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOnkmnwwKc8IGqDHSsO2ogau4rjvIZDiw',
    appId: '1:878367613942:ios:ed6f970a6fbed499529dd7',
    messagingSenderId: '878367613942',
    projectId: 'my-portfolio-9ff74',
    storageBucket: 'my-portfolio-9ff74.appspot.com',
    iosBundleId: 'com.example.newZap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOnkmnwwKc8IGqDHSsO2ogau4rjvIZDiw',
    appId: '1:878367613942:ios:1fef6bcb44aa2ad1529dd7',
    messagingSenderId: '878367613942',
    projectId: 'my-portfolio-9ff74',
    storageBucket: 'my-portfolio-9ff74.appspot.com',
    iosBundleId: 'com.example.newZap.RunnerTests',
  );
}
